# Generated by Django 4.2 on 2025-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringorder',
            name='address',
            field=models.TextField(default=1, help_text='Event venue or delivery location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cateringorder',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cateringorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cateringorder',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate Event'), ('House farming', 'House farming'), ('other event', 'other event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cateringorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
