# Generated by Django 4.2 on 2025-02-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cateringorder_address_cateringorder_special_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringorder',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_photos/'),
        ),
    ]
